[package]
description = "Easy server-client communication"
exclude = ["*"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]
license = "MIT"
name = "raphtalia/postman"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.0.4"

[dependencies]
Promise = "evaera/promise@3.2.1"
Signal = "sleitnick/signal@1.1.0"
t = "osyrisrblx/t@3.0.0"
