[package]
description = "Easy server-client communication"
name = "raphtalia/postman"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.0.0"

[dependencies]
t = "osyrisrblx/t@3.0.0"
